= Vent
:toc: macro

Vent is a Microblogging (twitter-like) application.
The purpose of this tutorial is to learn the basics of Clojure, with some guidance from a tutor.

toc::[]

== Application Structure

In src/tutorial/vent/lib.clj there are a number of functions which haven't yet been implemented.
The majority of challenges require:

. Fetching information from a "db" (A file on disk)
. Manipulating that data
. Writing new data to the db

There are 3 operations for the database:

`(db/reset)`:: This will reset the database to a known good state
`(db/store new-db)`:: Save a new version of the database
`(db/read)`:: Fetch the current version of the database

These are available in your REPL.

You will need to know the two data shapes that the application understands:

===  Vent

Vents are stored in the database as a _sequence_.
Each Vent has these keys:

[horizontal]
`:id`:: A globally unique id for this message, a number works.
`:text`:: The text of the actual vent
`:username`:: The username of the author, a string.
`:favorite?`:: (Optional) Either `true` or `false`, dictates where the tweet is a favorite.
`:author`::
	(Optional) The data of the User (see below) who created it. This should be added after reading from the database, it should not be stored in the database.

[source,clojure]
.An example Vent in the database
----
{:id 2
 :text "Lord but I dislike poetry. How can anyone remember words that aren't put to music?"
 :username "arl_the_bard"
 :favorite? true}
----

[source,clojure]
.An example Vent with an author attached
----
{:id 2
 :text "Lord but I dislike poetry. How can anyone remember words that aren't put to music?"
 :author {:name "Arliden"
          :following? true}
 :username "arl_the_bard"
 :favorite? true}
----

[source,clojure]
.How Vents look in the database
----
{:vents [{:id 1 :text "Text" :username "foo"} …]}
----

=== User

Users are stored in the database as a _map_.
This is like a dictionary or hash map in other languages.
The keys are usernames, and the values are Users.

Users look like so:
[horizontal]
`:name`:: A full name
`:follows`:: A list of usernames this user follows
`:following?`:: (Optional) `true` or `false`, defaults to false. Whether or not the user is being followed

[source,clojure]
.An example user
----
{:name "John Smith"
 :follows ["janesmith" "arl_the_bard"]
 :following? false}
----

[source,clojure]
.How users are stored in the database
----
{:users {"jsmith" {:name "John Smith"
                   :follows ["janesmith" "arl_the_bard"]
		   :following? true}
         "arl_the_bard" {:name "Arliden"
	                 :follows ["janesmith"]}}}
----


== Challenges

These can all be achieved by modifying files in src/tutorial/vent/lib.clj.

[[fetch_db_vents]]
=== Fetch database vents

Currently, the vents from `all` are hard-coded.
It would be great if `all` would return all the vents from the database.

=== Add author to vents

Depends on <<fetch_db_vents>>.

Now that vents are being fetched from the database, the user details are missing!
Fetch the user information from the database based on the `:username` key in the vent, and add it to the vents as the `:author` key.

[[favorites_list]]
=== Implement favorites list

Take the list of vents in the database, and filter them to show only the favorites on the favorites page.

=== Implement favorite button

You won't be able to see this working until you've done <<favorites_list>>.

Add the ability for the user to make a vent a favorite.

=== Implement Add Vent

Add the ability to create a new vent.

=== Implement Following page

Add the ability to see who you follow.

[[followers_list]]
=== Implement Followers page

Add the ability to see who your followers are.

=== Implement (un)Follow Button

You will need to complete <<followers_list>> to see this working.

There's (un)follow buttons on the followers/following page, but they don't change the followers list!
