= Vent

We've successfully impressed our Series A investors with our concept for "Vent".
Like Twitter, but better.
It'll have way more users.

We now have funding (which has been spent on the pizza you're eating) to finish off our MVP.

== Start the project

. Clone edge and go into the tutorial
+
[source,shell]
----
$ git clone --single-branch --branch tutorial https://github.com/juxt/edge.git
$ cd edge/tutorial.vent
----
. Start a REPL
+
[source,shell]
----
$ ../bin/rebel --cljs -A:dev:build:dev/build
----
. Start the server
+
[source,shell]
----
dev=> (go)
----

There is a front-end you can browse at link:http://localhost:3000[].

== Current structure

In src/tutorial/vent/lib.clj there are a number of functions which haven't yet been implemented.
The majority of your tasks are centered around:

. Fetching information from a "db" (A file on disk)
. Manipulating that data
. Writing new data to the db

There are 3 operations for the database:

`(db/reset)`:: This will reset the database to a known good state
`(db/store new-db)`:: Save a new version of the database
`(db/read)`:: Fetch the current version of the database

These are available in your REPL.

== Challenges

These can all be achieved by modifying files in src/tutorial/vent/lib.clj.

[[fetch_db_vents]]
=== Fetch database vents

Currently, the vents from `all` are hard-coded.
It would be great if `all` would return all the vents from the database.

=== Add author to vents

Depends on <<fetch_db_vents>>.

Now that vents are being fetched from the database, the user details are missing!
Fetch the user information from the database based on the `:username` key in the vent, and add it to the vents as the `:author` key.

[[favorites_list]]
=== Implement favorites list

Take the list of vents in the database, and filter them to show only the favorites on the favorites page.

=== Implement favorite button

You won't be able to see this working until you've done <<favorites_list>>.

Add the ability for the user to make a vent a favorite.

=== Implement Add Vent

Add the ability to create a new vent.

=== Implement Following page

Add the ability to see who you follow.

[[followers_list]]
=== Implement Followers page

Add the ability to see who your followers are.

=== Implement (un)Follow Button

You will need to complete <<followers_list>> to see this working.

There's (un)follow buttons on the followers/following page, but they don't change the followers list!
