= Swagger

See link:/swagger/index.html?url=/api/swagger.json[Swagger UI]

Rather than start with a Swagger specification and generate
boilerplate code, Edge encourages a fast-turnaround approach where the
API is declared in Clojure code/data, which generates Swagger
documentation and handles API requests at the same time. This ensures
the documentation is always aligned to the code.

Edge shows 2 different ways of publishing
https://swagger.io[Swagger] descriptions with
[.yada]#yada#. These descriptions have multiple uses. For example, you
can use a Swagger description to generate an API on Amazon Web
Services (AWS) using their API Gateway Tool, or of course to drive the
Swagger UI which is built in to Edge.

The first method is to use `yada/swaggered` to wrap a bidi structure
containing [.yada]#yada# resources. The disadvantage of this approach
is that the Swagger description is in the same URI hierarchy as your
API.

The second is more flexible, and allows you to publish your Swagger
descriptions separately from your API. This is the approach
demonstrated by the Phonebook example.
