= Edge

For newcomers to the Clojure language it can be quite a daunting task to put together a real Clojure application from scratch.

That's why we've done this initial step for you and creating a project that you can learn from and build upon.

This isn't merely a toy application. Edge represents JUXT's latest
thinking on the baseline architecture which we use for our own
professional Clojure projects. The name is taken from
link:https://en.wikipedia.org/wiki/Datum_reference[Datum edge].

== Features

Edge is a simple project demonstrating the integration of the following:

* link:https://clojure.org/guides/deps_and_cli[Clojure CLI with Deps]
* link:https://github.com/weavejester/integrant[Integrant]
* link:https://github.com/juxt/aero[Aero] configuration
* link:https://github.com/juxt/bidi[Bidi] routing
* API programming with link:https://github.com/juxt/yada[yada]
* Bruce Hauman's link:https://github.com/bhauman/rebel-readline[rebel-readline] REPL
* Single Page Application with ClojureScript
* Hiccup, Selmer, Aleph

== Getting started

Please see the <<app/README#>> for building and running the app.

== Why the `app` directory?

The rationale for using a sub-directory here is to allow for multiple
modules in a single repository. See <<docs/layout#>> for more details.

== Copyright & License

The MIT License (MIT)

Copyright © 2016-2018 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
