= How to build your own project upon Edge

Edge is designed to be built upon.
You are free to make whatever changes you like (additions and deletions), in accordance with the license.

== Licence

----
The MIT License (MIT)

Copyright © 2016-2018 JUXT LTD.

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
----

== Create a new "app"

From the root of the repo, run the `./bin/app` script.
It can be run with an optional flags which add support for sass or clojurescript, these are `--sass` and `--cljs` respectively.

NOTE: Your project name *must* be qualified including the company name (e.g. acme).

[source,shell]
----
$ ./bin/app acme/api
$ ./bin/app acme/blog --sass
$ ./bin/app acme/dashboard --cljs
$ ./bin/app acme/radar --sass --cljs
----

== Code

Keep around the additional libraries and integrations in edge around for as long as possible.
They're full of useful knowledge, and you never know when you might need to refer to them.
There's no harm in them sitting there if you never depend on them.

== Documentation

We think it's a good idea to continue to document your project as we've done with Edge. You might want to update the CSS stylesheet, source highlighting and other Asiidoctor attributes. They can be found in `doc/resources/doc/asciidoctor/attributes.edn`.

[source,clojure]
----
include::resource:doc/asciidoctor/attributes.edn[]
----

=== Updating the footer in HTML documentation

If the footer has a copyright declaration from JUXT, you can update
this by updating `doc/resources/doc/docinfo/docinfo-footer.html`. This
file name must not be changed as it is looked for by Asciidoctorj when
generating the HTML output.

[source,html]
----
include::resource:doc/docinfo/docinfo-footer.html[]
----
