= Developing on Edge

After creating your new application, you will now have a directory.

TIP: This guide will assume you named your program `acme/api`. Substitute as appropriate below.

== Shell

[source,shell]
.Enter the directory of your new app
----
edge$ cd acme.api
----

Once there you will find a deps.edn with a simple setup to get you going.
From here you can run a script to start a rebel-based REPL.

[source,shell]
.Run rebel REPL
----
acme.api$ ../bin/rebel -A:dev <1>
acme.api$ ../bin/rebel --cljs -A:dev:build:dev/build <2>
----
1: Run this if you have a simple application with no sass/cljs
2: Run this if you do have cljs in your project.

Options other than `--cljs` are passed straight through to the `clj` command line tool.

== CIDER/emacs

Versions more than 0.17 of CIDER support deps.edn seamlessly.

Open the file `edge/acme.api/deps.edn`.
From here you can use `cider-jack-in-clj`.

WARNING: CIDER attempts to stop & start a cljs repl, so `cider-jack-in-clj&cljs` may not work.  Fixes very welcome!

== (Neo)Vim

link:https://github.com/clojure-vim/vim-jack-in[vim-jack-in] can start a cider-based nREPL.
The edge authors use this.
In neovim it will use `:terminal`, but via `vim-dispatch` you can specify alternative starting strategies such as adjacent shells.

If you don't want to use that plugin, you can also try setting up nrepl in your user deps.edn file.

== [Your editor here]

Supporting more editors is on the roadmap.
However we don't use them all.
More editor instructions are welcome.
