= Set up your editor for Clojure

There's a number of good choices for Clojure editors.
This page will link you to the installation documentation for your editor, and provide some common config choices.

== Atom

Atom has two popular options.

link:https://atom.io/packages/proto-repl[ProtoREPL] is the older of the two, and is well established.
ProtoREPL has an link:https://git.io/atom_clojure_setup[Opinionated Setup Guide].

== Emacs

Emacs is a favourite in the Clojure community.
For emacs, the most popular package for integrating with Clojure is CIDER.

* link:http://www.cider.mx/en/latest/installation/[CIDER's installation].

If you're new to emacs, you should try link:https://www.braveclojure.com/basic-emacs/[].

== Intellij (Cursive)

If you're most at home in an IDE, you'll be looking for link:https://cursive-ide.com/[Cursive].
Free for non-commerical use, but you'll need a license for commercial use.

== Spacemacs

Spacemacs has a fantastic Clojure layer.
Find more information in the link:http://spacemacs.org/layers/+lang/clojure/README.html[Spacemacs layer README].

If you're new to Spacemacs, check out this video: link:https://www.youtube.com/watch?v=Uuwg-069NYE[]

== Vim

Vim's most popular package for Clojure integration is tpope's link:https://github.com/tpope/vim-fireplace[vim-fireplace].
It is commonly paired with link:https://github.com/guns/vim-sexp[vim-sexp] and/or link:https://github.com/eraserhd/parinfer-rust[parinfer].
Finally, for some convenience, you might want to add link:https://github.com/SevereOverfl0w/vim-replant[REPLant].

You can find a collection of hints on the JUXT blog at link:https://juxt.pro/blog/posts/vim-1.html[].

== VSCode

link:https://marketplace.visualstudio.com/items?itemName=cospaia.clojure4vscode[Calva] is a fantastic integration for Clojure with VSCode.
