= Edge: The Complete Manual
by JUXT
:edge-url-root: http://localhost:3000

Edge is a demonstration of a complete working website written in the
Clojure programming language, integrating a number of software
components and libraries,

== Introduction

The primary purpose of Edge is to act as a spring-board for serious
projects, and many developers have used it in this way to accelerate
their own project and improve their 'time-to-market'.

A secondary purpose of Edge is educational, and that is why this
document exists.

=== Who's is this for?

Edge is intended for both serious and educational use, including by
students learning Clojure as a programming language, school teachers,
college lecturers, as well as professional Clojure programmers in
small and large organisations.

=== Open Source

The complete system, including the Clojure language, the Java Virtual
Machine on which it runs, the Clojure code within Edge and the
numerous Clojure and Java libraries that are employed, are licensed
with open-source licenses.

=== Performant

Edge's design goals have included performance and scaleability, so is
ideal for websites that need to cope with a reasonably high volume of
web requests.

== A tour of Edge

We should start by introducing what Edge actually does.

NOTE: TBD


include::configuration.adoc[leveloffset=+1]

include::initialisation.adoc[leveloffset=+1]

include::components.adoc[leveloffset=+1]

include::yada.adoc[leveloffset=+1]

include::deployment.adoc[leveloffset=+1]

include::adaptation.adoc[leveloffset=+1]

include::bibliography.adoc[leveloffset=+1]
