= Edge: Developer's Guide
by JUXT
:edge-url-root: http://localhost:3000

Edge is a demonstration of a complete working website written in the
Clojure programming language, integrating a number of software
components and libraries,

== Introduction

The primary purpose of Edge is to act as a spring-board for serious
projects, and many developers have used it in this way to accelerate
their own project and improve their 'time-to-market'.

A secondary purpose of Edge is educational, and that is why this
document exists.

=== Audience

Developers who want to find out more about how Edge works in order to
build on it or learn how Clojure can be used to build a substantial
web-based system.

=== Open Source

The complete system, including the Clojure language, the Java Virtual
Machine on which it runs, the Clojure code within Edge and the
numerous Clojure and Java libraries that are employed, are licensed
with open-source licenses.

=== Performant

Edge has been designed with performance and scaleability in mind, so
is ideal for websites that need to cope with a reasonably high volume
of web requests.

include::configuration.adoc[leveloffset=+1]

include::initialisation.adoc[leveloffset=+1]

include::components.adoc[leveloffset=+1]

include::yada.adoc[leveloffset=+1]

include::deployment.adoc[leveloffset=+1]

include::adaptation.adoc[leveloffset=+1]
