= Moan

We've successfully impressed our Series A investors with our concept for "Moan".
Like Twitter, but better.
It'll have way more users.

We now have funding (which has been spent on the pizza you're eating) of funding to finish off our MVP.

== Current structure

There is a front-end you can browse at link:http://localhost:3000[].
The web resources are fully setup and working already.

In src/tutorial/moan/lib.clj there are a number of functions which haven't yet been implemented.
The majority of your tasks are centered around:

. Fetching information from a "db" (A file on disk)
. Manipulating that data
. Writing new data to the db

There are 3 operations for the database:

`(db/reset)`:: This will reset the database to a known good state
`(db/store new-db)`:: Save a new version of the database
`(db/read)`:: Fetch the current version of the database

These are available in your REPL.

== Challenges

You need to complete (A) challenges before working on (B) challenges.
Challenges with the same letter (e.g. all (A) challenges) can be completed in any order you fancy.

=== (A) Fetch real tweets

Currently, the tweets are hard-coded.
It would be great if `all` would return all the tweets from the database.

=== (B) Add author to tweets

Now that tweets are being fetched from the database, the user details are missing!
Fetch the user information from the database based on the `:username` key in the tweet, and add it to the tweets as the `:author` key.

=== (B) Implement favorites

Take the list of tweets in the database, and filter them to show only the
favorites on the favorites page.

=== (B) Implement favorite

Add the ability for the user to make a tweet a favorite.

=== (B) Implement Add Moan

Add the ability to create a new moan.
Assume the current user is anyone you like (or `overfl0w` if you are unsure).

=== (B) Implement Following page

Add the ability to see who you follow.

=== (B) Implement Followers page

Add the ability to see who your followers are.

=== (B) Implement (un)Follow Button

There's (un)follow buttons on the followers/following page, but they don't change the followers list!
